// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Get all categories",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CategoryListResponse"
                        }
                    }
                }
            }
        },
        "/categories/:id": {
            "delete": {
                "description": "Delete a category. Must be contained in no dreams.",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/categories/:id/name": {
            "patch": {
                "description": "Change the name of a category.",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "New name for this category",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/categories/:id/type": {
            "patch": {
                "description": "Change the type of a category.",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "New type for this category",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/categories/merge": {
            "post": {
                "description": "Merge two categories.",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "Which categories should be merged",
                        "name": "mergeCategoriesParams",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.MergeCategoriesParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CategoryListResponse"
                        }
                    }
                }
            }
        },
        "/count-categories": {
            "get": {
                "description": "Get count per category and person",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Counts by category and persons",
                        "schema": {
                            "$ref": "#/definitions/controller.CategoryListResponse"
                        }
                    }
                }
            }
        },
        "/count-categories/monthly": {
            "get": {
                "description": "Get count per month",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Monthly statistics",
                        "schema": {
                            "$ref": "#/definitions/controller.Statistics"
                        }
                    }
                }
            }
        },
        "/dreams": {
            "get": {
                "description": "Get all dreams",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "List of all dreams",
                        "schema": {
                            "$ref": "#/definitions/controller.DreamListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new dream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "The dream which will be created",
                        "name": "postDreamRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.PostDreamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/dreams/{dreamId}": {
            "get": {
                "description": "Get one dream",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "One dream",
                        "schema": {
                            "$ref": "#/definitions/controller.DreamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "Delete one dreams",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "patch": {
                "description": "Update an existing dream",
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "All parameters of the dream that should be updated",
                        "name": "updateDreamRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateDreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/dreams/{dreamId}/categories": {
            "post": {
                "description": "Add a new person or category to a dream",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "Name and category. Allowed values for 'category' are: 'person', 'category'",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.PostCategoryRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "number"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/dreams/{dreamId}/categories/{categoryId}": {
            "put": {
                "description": "Add an exiting person or category to a dream",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "Delete a category or person from a dream",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/dreams/{dreamId}/finalize": {
            "patch": {
                "description": "Finalize a dream",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CategoryListResponse": {
            "type": "object",
            "required": [
                "categories"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CategoryResponse"
                    }
                }
            }
        },
        "controller.CategoryResponse": {
            "type": "object",
            "required": [
                "id",
                "name",
                "type"
            ],
            "properties": {
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controller.CountByCat": {
            "type": "object",
            "required": [
                "categoryId",
                "count"
            ],
            "properties": {
                "categoryId": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "controller.DreamListResponse": {
            "type": "object",
            "required": [
                "dreams"
            ],
            "properties": {
                "dreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.DreamResponse"
                    }
                }
            }
        },
        "controller.DreamResponse": {
            "type": "object",
            "required": [
                "categories",
                "date",
                "description",
                "finalized",
                "id"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CategoryResponse"
                    }
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finalized": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                }
            }
        },
        "controller.MergeCategoriesParams": {
            "type": "object",
            "required": [
                "newName",
                "sourceCategoryId",
                "targetCategoryId"
            ],
            "properties": {
                "newName": {
                    "type": "string"
                },
                "sourceCategoryId": {
                    "type": "integer"
                },
                "targetCategoryId": {
                    "type": "integer"
                }
            }
        },
        "controller.PostCategoryRequestBody": {
            "type": "object",
            "required": [
                "categoryType",
                "name"
            ],
            "properties": {
                "categoryType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "controller.PostDreamRequest": {
            "type": "object",
            "required": [
                "date",
                "description"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "controller.Statistic": {
            "type": "object",
            "required": [
                "categories",
                "dreamCount",
                "month"
            ],
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.CountByCat"
                    }
                },
                "dreamCount": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                }
            }
        },
        "controller.Statistics": {
            "type": "object",
            "required": [
                "statistics"
            ],
            "properties": {
                "statistics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Statistic"
                    }
                }
            }
        },
        "controller.UpdateDreamRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
