// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dreams": {
            "get": {
                "description": "Get all dreams",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "List of all dreams",
                        "schema": {
                            "$ref": "#/definitions/controller.DreamsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new dream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "The dream which will be created",
                        "name": "dreamRequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DreamRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "number"
                        }
                    }
                }
            }
        },
        "/dreams/{dreamId}": {
            "get": {
                "description": "Get one dreams",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "One dream",
                        "schema": {
                            "$ref": "#/definitions/controller.DreamResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete one dreams",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "description": "Update an existing dream",
                "consumes": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "description": "The dream which will be updated",
                        "name": "dreamRequestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.DreamRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dreams/{dreamId}/tags": {
            "put": {
                "description": "Add a tag to a dream",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Label of tag",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.TagsResponse"
                        }
                    }
                }
            }
        },
        "/dreams/{dreamId}/tags/{tagId}": {
            "delete": {
                "description": "Remove a tag to a dream",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.TagsResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "Get all tags",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.TagsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.DreamRequestBody": {
            "type": "object",
            "required": [
                "date"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "controller.DreamResponse": {
            "type": "object",
            "required": [
                "date",
                "description",
                "id",
                "tags"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.TagResponse"
                    }
                }
            }
        },
        "controller.DreamsResponse": {
            "type": "object",
            "required": [
                "dreams"
            ],
            "properties": {
                "dreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.DreamResponse"
                    }
                }
            }
        },
        "controller.TagResponse": {
            "type": "object",
            "required": [
                "id",
                "title"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controller.TagsResponse": {
            "type": "object",
            "required": [
                "tags"
            ],
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.TagResponse"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
