definitions:
  controller.LoginRequest:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  controller.MergeCategoriesParams:
    properties:
      newName:
        type: string
      sourceCategoryId:
        type: integer
      targetCategoryId:
        type: integer
    required:
    - newName
    - sourceCategoryId
    - targetCategoryId
    type: object
  controller.PostCategoryRequestBody:
    properties:
      categoryType:
        $ref: '#/definitions/entity.CategoryType'
      name:
        type: string
    required:
    - categoryType
    - name
    type: object
  controller.PostDreamRequest:
    properties:
      date:
        type: string
      description:
        type: string
    required:
    - date
    type: object
  controller.UpdateDreamRequest:
    properties:
      date:
        type: string
      description:
        type: string
      rating:
        type: integer
    type: object
  entity.CategoriesCountResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/entity.CountByCat'
        type: array
    required:
    - categories
    type: object
  entity.CategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/entity.CategoryResponse'
        type: array
    required:
    - categories
    type: object
  entity.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        $ref: '#/definitions/entity.CategoryType'
    required:
    - id
    - name
    - type
    type: object
  entity.CategoryType:
    enum:
    - person
    - category
    type: string
    x-enum-varnames:
    - TypePerson
    - TypeCategory
  entity.CountByCat:
    properties:
      count:
        type: integer
      id:
        type: integer
    required:
    - count
    - id
    type: object
  entity.DreamResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/entity.CategoryResponse'
        type: array
      date:
        type: string
      description:
        type: string
      finalized:
        type: boolean
      id:
        type: integer
      rating:
        type: integer
      visible:
        type: boolean
    required:
    - categories
    - date
    - description
    - finalized
    - id
    - visible
    type: object
  entity.DreamsResponse:
    properties:
      dreams:
        items:
          $ref: '#/definitions/entity.DreamResponse'
        type: array
    required:
    - dreams
    type: object
  entity.LoginResponse:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  entity.Statistic:
    properties:
      categories:
        items:
          $ref: '#/definitions/entity.CountByCat'
        type: array
      dreamCount:
        type: integer
      month:
        type: string
    required:
    - categories
    - dreamCount
    - month
    type: object
  entity.Statistics:
    properties:
      statistics:
        items:
          $ref: '#/definitions/entity.Statistic'
        type: array
    required:
    - statistics
    type: object
info:
  contact: {}
paths:
  /categories:
    get:
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CategoriesResponse'
  /categories/:id:
    delete:
      description: Delete a category. Must be contained in no dreams.
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /categories/:id/name:
    patch:
      description: Change the name of a category.
      parameters:
      - description: New name for this category
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /categories/:id/type:
    patch:
      description: Change the type of a category.
      parameters:
      - description: New type for this category
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /categories/merge:
    post:
      description: Merge two categories.
      parameters:
      - description: Which categories should be merged
        in: body
        name: mergeCategoriesParams
        required: true
        schema:
          $ref: '#/definitions/controller.MergeCategoriesParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CategoriesCountResponse'
  /count-categories:
    get:
      description: Get count per category and person
      parameters:
      - description: Limit of returned results
        in: query
        name: limit
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: Counts by category and persons
          schema:
            $ref: '#/definitions/entity.CategoriesCountResponse'
  /count-categories/monthly:
    get:
      description: Get count per month
      produces:
      - application/json
      responses:
        "200":
          description: Monthly statistics
          schema:
            $ref: '#/definitions/entity.Statistics'
  /dreams:
    get:
      description: Get all dreams
      produces:
      - application/json
      responses:
        "200":
          description: List of all dreams
          schema:
            $ref: '#/definitions/entity.DreamsResponse'
    post:
      consumes:
      - application/json
      description: Create a new dream
      parameters:
      - description: The dream which will be created
        in: body
        name: postDreamRequest
        required: true
        schema:
          $ref: '#/definitions/controller.PostDreamRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: number
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /dreams/{dreamId}:
    delete:
      description: Delete one dreams
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
        "404":
          description: Not Found
    get:
      description: Get one dream
      produces:
      - application/json
      responses:
        "200":
          description: One dream
          schema:
            $ref: '#/definitions/entity.DreamResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
    patch:
      consumes:
      - application/json
      description: Update an existing dream
      parameters:
      - description: All parameters of the dream that should be updated
        in: body
        name: updateDreamRequest
        required: true
        schema:
          $ref: '#/definitions/controller.UpdateDreamRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/categories:
    post:
      description: Add a new person or category to a dream
      parameters:
      - description: 'Name and category. Allowed values for ''catgory'' are: ''person'',
          ''category'''
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/controller.PostCategoryRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: number
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/categories/{categoryId}:
    delete:
      description: Delete a category or person from a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
    put:
      description: Add an exiting person or category to a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/finalize:
    patch:
      description: Finalize a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/private:
    get:
      description: Get all dreams - including private
      produces:
      - application/json
      responses:
        "200":
          description: List of all dreams
          schema:
            $ref: '#/definitions/entity.DreamsResponse'
      security:
      - BasicAuth: []
  /dreams/private/{dreamId}:
    get:
      description: Get one private dream
      produces:
      - application/json
      responses:
        "200":
          description: One dream
          schema:
            $ref: '#/definitions/entity.DreamResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      security:
      - BasicAuth: []
    patch:
      description: Toggle visibility of a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BasicAuth: []
  /login:
    post:
      description: Login
      parameters:
      - description: Password and user name
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/controller.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.LoginResponse'
        "400":
          description: Bad Request
  /logout:
    post:
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
swagger: "2.0"
