definitions:
  entity.CategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/entity.CategoryResponse'
        type: array
    required:
    - categories
    type: object
  entity.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  entity.CountResponse:
    properties:
      count:
        type: integer
      id:
        type: integer
    required:
    - count
    - id
    type: object
  entity.CountsResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/entity.CountResponse'
        type: array
      persons:
        items:
          $ref: '#/definitions/entity.CountResponse'
        type: array
    required:
    - categories
    - persons
    type: object
  entity.DreamMetaResponse:
    properties:
      date:
        type: string
      id:
        type: integer
      visible:
        type: boolean
    required:
    - date
    - id
    - visible
    type: object
  entity.DreamResponse:
    properties:
      categories:
        $ref: '#/definitions/entity.CategoriesResponse'
      date:
        type: string
      description:
        type: string
      id:
        type: integer
      persons:
        $ref: '#/definitions/entity.PersonsResponse'
      visible:
        type: boolean
    required:
    - categories
    - date
    - description
    - id
    - persons
    - visible
    type: object
  entity.DreamsResponse:
    properties:
      dreams:
        items:
          $ref: '#/definitions/entity.DreamMetaResponse'
        type: array
    required:
    - dreams
    type: object
  entity.PersonResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  entity.PersonsResponse:
    properties:
      persons:
        items:
          $ref: '#/definitions/entity.PersonResponse'
        type: array
    required:
    - persons
    type: object
  v1.DreamRequestBody:
    properties:
      date:
        type: string
      description:
        type: string
    required:
    - date
    type: object
info:
  contact: {}
paths:
  /categories:
    get:
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CategoriesResponse'
  /dreams:
    get:
      description: Get all dreams
      produces:
      - application/json
      responses:
        "200":
          description: List of all dreams
          schema:
            $ref: '#/definitions/entity.DreamsResponse'
    post:
      consumes:
      - application/json
      description: Create a new dream
      parameters:
      - description: The dream which will be created
        in: body
        name: dreamRequestBody
        required: true
        schema:
          $ref: '#/definitions/v1.DreamRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: number
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /dreams/{dreamId}:
    delete:
      description: Delete one dreams
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
        "404":
          description: Not Found
    get:
      description: Get one dream
      produces:
      - application/json
      responses:
        "200":
          description: One dream
          schema:
            $ref: '#/definitions/entity.DreamResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
    patch:
      consumes:
      - application/json
      description: Update an existing dream
      parameters:
      - description: The dream which will be updated
        in: body
        name: dreamRequestBody
        required: true
        schema:
          $ref: '#/definitions/v1.DreamRequestBody'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/categories:
    put:
      description: Add a category to a dream
      parameters:
      - description: Name of a category
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CategoriesResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/categories/{categoryId}:
    delete:
      description: Remove a category from a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CategoriesResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/persons:
    put:
      description: Add a person to a dream
      parameters:
      - description: Name of person
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PersonsResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/{dreamId}/persons/{personId}:
    delete:
      description: Delete a person from a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PersonsResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
  /dreams/private:
    get:
      description: Get all dreams - including private
      produces:
      - application/json
      responses:
        "200":
          description: List of all dreams
          schema:
            $ref: '#/definitions/entity.DreamsResponse'
  /dreams/private/{dreamId}:
    get:
      description: Get one private dream
      produces:
      - application/json
      responses:
        "200":
          description: One dream
          schema:
            $ref: '#/definitions/entity.DreamResponse'
        "400":
          description: Bad Request
        "404":
          description: Not Found
    patch:
      description: Toggle visibility of a dream
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /persons:
    get:
      description: Get all persons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.PersonsResponse'
  /private/statistics:
    get:
      description: Get count per category and person
      parameters:
      - description: Limit of returned results
        in: query
        name: limit
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: Counts by category and persons
          schema:
            $ref: '#/definitions/entity.CountsResponse'
  /statistics:
    get:
      description: Get count per category and person
      parameters:
      - description: Limit of returned results
        in: query
        name: limit
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: Counts by category and persons
          schema:
            $ref: '#/definitions/entity.CountsResponse'
swagger: "2.0"
