name: CI

on:
  push:
    tags: 
      - 'v*'
    branches:
      - '**'
  workflow_dispatch:

env:
    IMAGE_NAME: dreams-api
    DOCKER_USERNAME: bbrighter

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions: 
        contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Check go version
      run: |
        GO_MOD_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
        GO_DOCKER_VERSION=$(grep '^ARG GO_VERSION=' Dockerfile | awk -F'"' '{print $2}')
        if [ "$GO_MOD_VERSION" != "$GO_DOCKER_VERSION" ]; then
            echo "Go version mismatch: go.mod ($GO_MOD_VERSION) vs Dockerfile ($GO_DOCKER_VERSION)"
            exit 1
        else
            echo "Go versions match: $GO_MOD_VERSION"
        fi

          
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: go.mod

    - name: Download dependencies
      run: go mod download
    
    - name: Check licenses
      run: go tool go-licenses check ./... --allowed_licenses 'MIT,Apache-2.0,BSD-3-Clause'
    
    - name: Test
      run: go test -v ./...
  
  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v') && success()
    runs-on: ubuntu-24.04
    permissions: 
        contents: read

    steps:   
    - name: Checkout
      uses: actions/checkout@v7

    - name: Log in to Docker
      uses: docker/login-action@v4
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v7 
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/arm64
        cache-from: |
          type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        cache-to: type=inline


